// good code lol

#define SCREEN_WIDTH 800
#define SCREEN_HEIGHT 600

#define MAP_SIZE 96

#define TILE_HEIGHT 8
#define TILE_WIDTH 8

#define MAP_RENDER_AREA 24

#define MAP_RENDER_OFFSET_X ((SCREEN_WIDTH - (TILE_WIDTH * MAP_RENDER_AREA)) / 2)
#define MAP_RENDER_OFFSET_Y 425
